name: Publish packages to PyPI

on:
  push:
    tags:
      - "*"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.x
    - name: Install dependencies
      run: pip install pep517
    - name: Create packages
      run: python -m pep517.build --source --binary --out-dir dist/
    - name: Upload packages
      uses: pypa/gh-action-pypi-publish@v1.0.0a0
      with:
        user: ${{ secrets.pypi_username }}
        password: ${{ secrets.pypi_password }}
