name: Run the test suite

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  pyright:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.x
    - uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: pip-pyright
    - name: Install dependencies
      run: pip install -e . pyright pytest
    - name: Run pyright
      run: pyright --verifytypes smtpproto

  test:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: pip
        cache-dependency-path: pyproject.toml
    - name: Install dependencies
      run: |
        pip install aiosmtpd@git+https://github.com/maxking/aiosmtpd.git@py311
        pip install .[test] coveralls
    - name: Test with pytest
      run: coverage run -m pytest
    - name: Upload coverage data to Coveralls
      run: coveralls --service=github
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        COVERALLS_FLAG_NAME: ${{ matrix.test-name }}
        COVERALLS_PARALLEL: true

  coveralls:
    name: Finish Coveralls
    needs: test
    runs-on: ubuntu-latest
    container: python:3-slim
    steps:
    - name: Finished
      run: |
        pip install coveralls
        coveralls --service=github --finish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
